project_id = "ixblicchtdnqzeyrfqhi"

[functions.clock-in-out]
verify_jwt = true

[functions.daily-attendance-notifications]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.annual-leave-allocation]
verify_jwt = false

[functions.weekly-exception-report]
verify_jwt = false